spring:
    application:
        name: service2
    profiles:
        active: dev
    config:
        import: optional:configserver:http://localhost:9000

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url.defaultZone: http://localhost:8888/eureka
